kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dream-stream-pv-claim
  #namespace: rook-ceph
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi #Should be changed to the capacity of the external drive.