apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: broker-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: broker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50