apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-monitor
  labels:
    prometheus: monitor
spec:
  version: v1.3.0
  # Define that all ServiceMonitor TPRs with the label `tier = frontend` should be included
  # into the server's configuration.
  serviceMonitorNamespaceSelector: {} # auto discover all service monitors accross all namespaces
  serviceMonitorSelector: {} # auto discover all service monitors in namespaces configured one line above
  serviceMonitors:
  - selector:
      matchLabels:
        monitor: enable