{
 "title": "Dream-Stream / Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Producer - Messages Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_published) by (pod)",
     "legendFormat": "messages published {{pod}}"
    },
    { "expr": "sum(messages_published)", "legendFormat": "messages published total" },
    {
     "expr": "sum(batch_messages_published) by (pod)",
     "legendFormat": "batch messages published {{pod}}"
    },
    {
     "expr": "sum(batch_messages_published) by (pod)",
     "legendFormat": "batch messages published total"
    }
   ]
  },
  {
   "title": "Broker - Messages Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_received) by (pod)",
     "legendFormat": "messages received {{pod}}"
    },
    { "expr": "sum(messages_received)", "legendFormat": "messages received total" },
    {
     "expr": "sum(message_batches_received) by (pod)",
     "legendFormat": "batch messages received {{pod}}"
    },
    { "expr": "sum(message_batches_received)", "legendFormat": "batch messages received total" }
   ]
  },
  {
   "title": "Consumer - Messages Consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_consumed) by (pod)",
     "legendFormat": "messages consumed {{pod}}"
    },
    { "expr": "sum(messages_consumed)", "legendFormat": "messages consumed total" },
    {
     "expr": "sum(batched_messages_consumed) by (pod)",
     "legendFormat": "batch messages consumed {{pod}}"
    },
    {
     "expr": "sum(batched_messages_consumed) by (pod)",
     "legendFormat": "batch messages consumed total"
    }
   ]
  },
  {
   "title": "Producer - Messages Sent Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_published[2m])) by (pod)",
     "legendFormat": "messages published pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_published[2m]))",
     "legendFormat": "messages published pr sec total"
    },
    {
     "expr": "sum(rate (batch_messages_published[2m])) by (pod)",
     "legendFormat": "batch messages published pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (batch_messages_published[2m]))",
     "legendFormat": "batch messages published pr sec total"
    }
   ]
  },
  {
   "title": "Broker - Messages Received Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_received[2m])) by (pod)",
     "legendFormat": "messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_received[2m]))",
     "legendFormat": "messages received pr sec total"
    },
    {
     "expr": "sum(rate (message_batches_received[2m])) by (pod)",
     "legendFormat": "batch messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (message_batches_received[2m]))",
     "legendFormat": "batch messages received pr sec total"
    }
   ]
  },
  {
   "title": "Consumer - Messages Consumed Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_consumed[2m])) by (pod)",
     "legendFormat": "messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_consumed[2m]))",
     "legendFormat": "messages consumed pr sec total"
    },
    {
     "expr": "sum(rate (batched_messages_consumed[2m])) by (pod)",
     "legendFormat": "batch messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (batched_messages_consumed[2m]))",
     "legendFormat": "batch messages consumed pr sec total"
    }
   ]
  },
  {
   "title": "Producer - Topic Partition Split",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (messages_published) by (TopicPartition)",
     "legendFormat": "messages batched {{TopicPartition}}"
    }
   ]
  },
  {
   "title": "Broker - Topic Partition Split",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_received) by (TopicPartition)",
     "legendFormat": "messages received {{pod}}"
    }
   ]
  },
  {
   "title": "Storage API - Data Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_written_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Producer - Data Published",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_published_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Broker - Data Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_received_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Storage API - Data Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_read_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Broker - Data Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_sent_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Storage API - Corrupt Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(corrupted_messages_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  }
 ]
}