{
 "title": "Dream-Stream / Evaluation Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer - Messages Sent Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (main_messages_published{ApplicationType=\"Kafka\"}[2m])) by (pod)",
     "legendFormat": "messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (main_messages_published{ApplicationType=\"Kafka\"}[2m]))",
     "legendFormat": "messages received pr sec total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"})",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"})",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"})",
     "legendFormat": "etcd"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"}) + \nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}) + \nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}) +\nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Consumer - Messages Consumed Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_consumed{TopicPartition=\"Kafka\"}[2m])) by (pod)",
     "legendFormat": "messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_consumed{TopicPartition=\"Kafka\"}[2m]))",
     "legendFormat": "messages consumed pr sec total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "producers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "zookeeper"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"}[1m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[1m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit) - Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node-exporter\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node-exporter\"})",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}