apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-storage
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  hostPath:
    path: /ssd/nfs
    type: DirectoryOrCreate