{
 "title": "Dream-Stream / Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Producer - Messages Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_published) by (pod)",
     "legendFormat": "messages published {{pod}}"
    },
    { "expr": "sum(messages_published)", "legendFormat": "messages published total" },
    {
     "expr": "sum(batch_messages_published) by (pod)",
     "legendFormat": "batch messages published {{pod}}"
    },
    {
     "expr": "sum(batch_messages_published) by (pod)",
     "legendFormat": "batch messages published total"
    }
   ]
  },
  {
   "title": "Broker - Messages Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_received) by (pod)",
     "legendFormat": "messages received {{pod}}"
    },
    { "expr": "sum(messages_received)", "legendFormat": "messages received total" },
    {
     "expr": "sum(message_batches_received) by (pod)",
     "legendFormat": "batch messages received {{pod}}"
    },
    { "expr": "sum(message_batches_received)", "legendFormat": "batch messages received total" }
   ]
  },
  {
   "title": "Consumer - Messages Consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_consumed) by (pod)",
     "legendFormat": "messages consumed {{pod}}"
    },
    { "expr": "sum(messages_consumed)", "legendFormat": "messages consumed total" },
    {
     "expr": "sum(batched_messages_consumed) by (pod)",
     "legendFormat": "batch messages consumed {{pod}}"
    },
    {
     "expr": "sum(batched_messages_consumed) by (pod)",
     "legendFormat": "batch messages consumed total"
    }
   ]
  },
  {
   "title": "Producer - Messages Sent Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_published[2m])) by (pod)",
     "legendFormat": "messages published pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_published[2m]))",
     "legendFormat": "messages published pr sec total"
    },
    {
     "expr": "sum(rate (batch_messages_published[2m])) by (pod)",
     "legendFormat": "batch messages published pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (batch_messages_published[2m]))",
     "legendFormat": "batch messages published pr sec total"
    }
   ]
  },
  {
   "title": "Broker - Messages Received Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_received[2m])) by (pod)",
     "legendFormat": "messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_received[2m]))",
     "legendFormat": "messages received pr sec total"
    },
    {
     "expr": "sum(rate (message_batches_received[2m])) by (pod)",
     "legendFormat": "batch messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (message_batches_received[2m]))",
     "legendFormat": "batch messages received pr sec total"
    }
   ]
  },
  {
   "title": "Consumer - Messages Consumed Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_consumed[2m])) by (pod)",
     "legendFormat": "messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_consumed[2m]))",
     "legendFormat": "messages consumed pr sec total"
    },
    {
     "expr": "sum(rate (batched_messages_consumed[2m])) by (pod)",
     "legendFormat": "batch messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (batched_messages_consumed[2m]))",
     "legendFormat": "batch messages consumed pr sec total"
    }
   ]
  },
  {
   "title": "Producer - Topic Partition Split",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (messages_published) by (TopicPartition)",
     "legendFormat": "messages batched {{TopicPartition}}"
    }
   ]
  },
  {
   "title": "Broker - Topic Partition Split",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_received) by (TopicPartition)",
     "legendFormat": "messages received {{pod}}"
    }
   ]
  },
  {
   "title": "Storage API - Data Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_written_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Producer - Data Published",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_published_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Broker - Data Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_received_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Storage API - Data Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_read_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Broker - Data Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(messages_sent_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  },
  {
   "title": "Storage API - Corrupt Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(corrupted_messages_size_in_bytes) by (pod)",
     "legendFormat": "messages batched {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Dream-Stream / Kubernetes / Compute Resources / Pod",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   },
   { "name": "interval", "query": "4h" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", service=\"kubelet\"}[1m])) by (pod)",
     "legendFormat": "Pod CPU"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", service=\"kubelet\"}) by (pod)",
     "legendFormat": "Pod Memory"
    }
   ]
  }
 ]
}
{
 "title": "Dream-Stream / Resources",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dream-Stream CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "producers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "etcd"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"}[1m])) + sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[1m])) + sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m])) + sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Dream-Stream Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"})",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"})",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"})",
     "legendFormat": "etcd"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"}) + sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}) + sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m])) + sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}
{
 "title": "Dream-Stream / StatefulSets",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_statefulset_metadata_generation, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "statefulset",
    "label": "Name",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Current Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\", cluster=\"$cluster\", namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\", cluster=\"$cluster\", namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"$statefulset\", cluster=\"$cluster\", namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"$statefulset\", cluster=\"$cluster\", namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"$statefulset\", cluster=\"$cluster\", namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Requested CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"$statefulset.*\"})"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas of current version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  }
 ]
}
{
 "title": "Dream-Stream / Load vs Broker Replicas",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Broker - Messages Received Pr Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_received[2m])) by (pod)",
     "legendFormat": "messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_received[2m]))",
     "legendFormat": "messages received pr sec total"
    },
    {
     "expr": "sum(rate (message_batches_received[2m])) by (pod)",
     "legendFormat": "batch messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (message_batches_received[2m]))",
     "legendFormat": "batch messages received pr sec total"
    }
   ]
  },
  {
   "title": "Broker Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"broker\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "Broker Count"
    }
   ]
  }
 ]
}
{
 "title": "Dream-Stream / Evaluation Dream-Stream",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Broker - Messages Received Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_received[2m])) by (pod)",
     "legendFormat": "messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_received[2m]))",
     "legendFormat": "messages received pr sec total"
    },
    {
     "expr": "sum(rate (message_batches_received[2m])) by (pod)",
     "legendFormat": "batch messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (message_batches_received[2m]))",
     "legendFormat": "batch messages received pr sec total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"})",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"})",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"})",
     "legendFormat": "etcd"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"storage-api-.*\", service=\"kubelet\"})",
     "legendFormat": "storage-api"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"}) + \nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}) + \nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}) +\nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"}) +\nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"storage-api-.*\", service=\"kubelet\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Consumer - Messages Consumed Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_consumed[2m])) by (pod)",
     "legendFormat": "messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_consumed[2m]))",
     "legendFormat": "messages consumed pr sec total"
    },
    {
     "expr": "sum(rate (batched_messages_consumed[2m])) by (pod)",
     "legendFormat": "batch messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (batched_messages_consumed[2m]))",
     "legendFormat": "batch messages consumed pr sec total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"}[2m]))",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[2m]))",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[2m]))",
     "legendFormat": "producers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"}[2m]))",
     "legendFormat": "etcd"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"storage-api-.*\", service=\"kubelet\"}[2m]))",
     "legendFormat": "storage-api"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"broker.*\", service=\"kubelet\"}[2m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[2m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[2m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"etcd-.*\", service=\"kubelet\"}[2m])) +\nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"storage-api-.*\", service=\"kubelet\"}[2m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"broker\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"broker\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"broker\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"broker\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"broker\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit) - Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node-exporter\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node-exporter\"})",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}
{
 "title": "Dream-Stream / Evaluation Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer - Messages Sent Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (main_messages_published{ApplicationType=\"Kafka\"}[2m])) by (pod)",
     "legendFormat": "messages received pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (main_messages_published{ApplicationType=\"Kafka\"}[2m]))",
     "legendFormat": "messages received pr sec total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"})",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"})",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"})",
     "legendFormat": "etcd"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"}) + \nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}) + \nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}) +\nsum(container_memory_usage_bytes{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Consumer - Messages Consumed Pr Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (messages_consumed{TopicPartition=\"Kafka\"}[2m])) by (pod)",
     "legendFormat": "messages consumed pr sec {{pod}}"
    },
    {
     "expr": "sum(rate (messages_consumed{TopicPartition=\"Kafka\"}[2m]))",
     "legendFormat": "messages consumed pr sec total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "brokers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "consumers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "producers"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "zookeeper"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"kf-kafka.*\", service=\"kubelet\"}[1m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"consumer.*\", service=\"kubelet\"}[1m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"evaluation-producer-.*\", service=\"kubelet\"}[1m])) + \nsum (rate (container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"zookeeper-.*\", service=\"kubelet\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"kf-kafka\", namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit) - Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node-exporter\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node-exporter\"})",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}