apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    chart: etcd-0.7.3
    heritage: Helm
    release: etcd
  name: etcd-external
spec:
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
    release: etcd
  sessionAffinity: None
  type: LoadBalancer